config/routes.rb
Rails.application.routes.draw do
  get '/profile', to: 'profiles#profile', as: 'profile'
  devise_for :users
  root to: 'pages#home'
  resources :cars do
    resources :bookings, only: [:new, :create, :show]
    resources :profiles, only: [:edit]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  include AlgoliaSearch

  belongs_to :user
  has_many :bookings, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :make, presence: true
  validates :rental_rate, presence: true
  # validates :registration_number, presence: true
  validates :photo, presence: true
  validates :description, presence: true


      mount_uploader :photo, PhotoUploader

  algoliasearch do
    attribute :make, :rental_rate, :description

    # customRanking ['desc(rental_rate)']

  end


end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one :profile
  before_create :build_profile


  # validates :location, presence: true
  # validates :name, presence: true
  # validates :driving_license, acceptance: true
  # validates :date_of_birth, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:location])

    # For additional in app/views/devise/registrations/edit.html.erb
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
    @booking.price = @car.rental_rate * (params[:booking]["end_date(3i)"].to_i  - params[:booking]["start_date(3i)"].to_i)
    authorize @booking
    if @booking.save
      redirect_to profile_path(current_user)
    end
  end

  def show
    @car = Car.find(params[:car_id])
    @booking = Booking.find(params[:id])
    authorize @booking
    @car = Car.new
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = policy_scope(Car)
    authorize @cars

    if params[:address].present?
      @cars = Car.near(params[:address], 100)
    else
      @cars = policy_scope(Car)
    end


  end

  def show
    @car = Car.find(params[:id])
    @user = User.find(@car.user_id)
    @booking = Booking.new

    @markers =
      {
        lat: @car.latitude,
        lng: @car.longitude#,
        # infoWindow: { content: render_to_string(partial: "/cars/map_box", locals: { car: car }) }
      }
  end

  def new
    @car = Car.new
    authorize @car
  end

  def edit

  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    @car.address = current_user.location
    authorize @car

    if @car.save
      redirect_to cars_path
    else
      render "new"
    end

  end

  def update
    if @car.update(car_params)
      redirect_to cars_path
    else
      render :edit
    end
    authorize @car
  end

  def destroy
    if @car.destroy
      redirect_to cars_path
    end
    authorize @car
  end

  private

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end

  def car_params
    params.require(:car).permit("make", "rental_rate", "description", "photo", "available", "user_id")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @cars = Car.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include Pundit
  after_action :verify_authorized, except: [:profile]

  def edit
    @profile = Profile.find_by user_id: current_user.id
    @attributes = Profile.attribute_names - %w(id user_id created_at updated_at)
  end

  def profile
    # @user = current_user
    # authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <h1 class="header1"> Your Booking Details </h1>

      <div class="message">
        <%= cl_image_tag @car.photo, id: "car_booking" %>
        <!--  <img src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan" -->
        <div class="message-name">
          <h3><strong><%=@booking.car.make.capitalize %></strong></h3>
          <p> <%= @booking.start_date %> to <%= @booking.end_date %></p>
        </div>
        <div class="message-body">
          <h3><strong>Your car details</strong></h3>
          <p> <%= @booking.car.description %> </p>
        </div>
        <div class="message-status">
          <h3 class="status pending"><strong>Pending</strong></h3>
          <p class="price"> £ <%= @booking.price %></p>
        </div>
      </div>

      <div class="links-to-pages">
        <%= link_to "home", root_path %>
        <%= link_to "view more cars", cars_path %>
      </div>
    </div>
  </div>
</div>

app/views/cars/_booking_form.html.erb
<%= simple_form_for([@car, @booking]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date, as: :string, input_html: { class: "datepicker start", id: "black-input"} %>
    <%= f.input :end_date, as: :string, input_html: { class: "datepicker", id: "black-input"}   %>
  </div>

  <!-- <div class="fhold">
    <input  class="start datepicker" name="start_date" type="datetime-local" placeholder="Start date" />
    <input class="datepicker" name="end_date" type="datetime-local" placeholder="End date" />
  </div> -->

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cars/_form.html.erb
<div class="form container">
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8 form-column">
      <h2> Add a new Car </h2>
      <%= simple_form_for(@car) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :make, required: false, label: "Make of Vehicle", prompt: "Make" %>
        <%= f.input :rental_rate, required: false %>
        <%= f.input :description, required: false %>
        <%= f.input :photo, required: false %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :available, required: false %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, :class => "create-button" %>
      </div>
      <%= link_to 'Back', cars_path%>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/_show_owner.html.erb
    <div class="links">
      <%= link_to 'Edit', edit_car_path(@car) %> |
      <%= link_to 'Back', cars_path %> |
      <%= link_to 'Destroy', @car, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>

app/views/cars/edit.html.erb
<h1> Edit a Car </h1>
<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<div class="index-container">
    <div class="car-header">
      <h3>Select your ride</h3>
    </div>
  <div class="row">
    <% @cars.each do |car| %>
    <div class="col-xs-4">
      <%= link_to car_path(car) do %>
        <% if car.photo != nil %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path car.photo %>);">
        <% else %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
        <% end %>
          <div class="card-category"></div>
          <div class="card-description">
            <p><%= car.make %></p>
            <p>£<%= car.rental_rate %> per day</p>
            <!-- <p><%= car.description %></p> -->
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="wrapper">
    <%= render 'form' %>
</div>

app/views/cars/show.html.erb
<div class="main-section">

 <div class="container">
    <div class="car-header">
      <h3><%= @car.make %> - £<%= @car.rental_rate %> for just per day </h3>
    </div>

  <div class="centrepiece-container">

    <div class="form">
      <div>
        <%= image_tag "#{@car.photo}", id: "car", :class => "center", :style => "width: 100%" %>
      </div>
      <div class='car-details-container'>
        <p id="car-details">
          <%= @car.description  %>
        </p>
        <% if current_user.id == @car.user_id  %>
          <%= render 'cars/show_owner' %>
        <% else %>
          <%= render 'cars/booking_form' %>
        <% end %>
      </div>
    </div>

    <div id="map" class="item" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>">
    </div>

  </div>


 </div>
</div>




<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
<%= javascript_pack_tag "map" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RENT-MY-WHEELS</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- NEW! -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1516370710288-61c18f5ed3a6?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=57bcb643e2dad6c0b2199671f55b0052&auto=format&fit=crop&w=1350&q=80');">
  <div class="card-category">£<%= car.rental_rate %></div>
  <div class="card-description">
    <h2><%= car.make %></h2>
    <p><%= car.description %></p>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <%= link_to '', car_path(car), class: "card-link" %>
</div>

app/views/pages/_cards.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <% @cars.each do |c| %>
      <div class="col-xs-12 col-sm-4">
        <%= render 'pages/card', car: c %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>
  
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/_searchform.html.erb
<form action="/cars" method="get" >
  <div class="fhold">
    <input class="searcher" name="search" type="text" placeholder="Address or Postcode..."/>
  </div>
  <div class="">
    <input  class="start datepicker" name="start_date" type="datetime-local" placeholder="Start date" />
    <input class="datepicker" name="end_date" type="datetime-local" placeholder="End date" />
  </div>

  <div class="fhold">
    <input name="commit" type="submit" value="Search" class="button" />
  </div>
</form>

app/views/pages/home.html.erb
<div id="banner">
  <div class="banner-content">
    <h1>Easy Car Rental: <strong>Just click and drive</strong></h1>
    <p>Making car sharing a doddle</p>
    <%= render 'pages/searchform' %>
   </div>
</div>

app/views/profiles/profile.html.erb
<div class="wrapper">

<h1 class="header1"> Your Profile page </h1>

<div class="profile-cards">
  <% current_user.bookings.each do |booking| %>
  <% if booking.car.photo? %>
  <% photo = cl_image_path booking.car.photo %>
  <% else %>
  <% photo = image_path "car_copy.jpg" %>
  <% end %>
    <div class="profile-card">
      <%= link_to car_booking_path(booking.car, booking) do %>
        <div class="car-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= photo %>);">
          <div class="price">
            <span>£<%= booking.car.rental_rate %></span>

          </div>
        </div>
        <div class="car-info">
          <h2>Contratulations!</h2>
          <p>You've booked <%= booking.car.make %></p>
          <p><%= booking.start_date %> - <%= booking.end_date %></p>
          <%= link_to "Pick up your car here", "#" %>
        </div>
      <% end %>
    </div>


  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert" style="margin-top: 70px;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="foot text-center"> <strong> RENT MY WHEELS </strong> &copy;  2018 Corporate Registration No.: 06849930 Contact us on.   <a href="#" class="fa fa-facebook"></a>
<a href="#" class="fa fa-twitter"></a>
<a href="#" class="fa fa-instagram"></a>
<a href="#" class="fa fa-linkedin"></a>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon sticky">
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "https://image.flaticon.com/icons/svg/2/2087.svg", alt: "logo" %>
  </a>

  <!-- Right Navigation -->
  <% if user_signed_in? %>
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to destroy_user_session_path, method: :delete do %>
    <%= t(".sign_out", default: "Logout") %>
    <% end %>
    <% else %>
    <%= link_to new_user_session_path do  %>
    <%= t(".sign_in", default: "Login") %>
    <% end %>
    <% end %>

    <%= link_to 'New Car', new_car_path %>

  <!--     <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
      <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
      <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a> -->

      <!-- Profile picture with dropdown list -->

      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "download.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown", alt: "Profile picture" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Profile", profile_path %></li>
            <li> <%= link_to "Settings", edit_user_registration_path %></li>
            <li>  <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Logout") %> </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>


  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>